#2026-04-04 11:20
# act-android.yml
name: act - Android CI

on:
#  pull_request:
#    paths-ignore:
#      - '.idea/**'
#      - '.gitattributes'
#      - '.github/**.json'
#      - '.gitignore'
#      - '.gitmodules'
#      - '**.md'
#      - 'LICENSE'
#      - 'NOTICE'
  workflow_dispatch:

env:
  PRG_NAME: "OpenKeychain"
  PRG_VERSION: "v6.0.4"
  TAG_NAME: "OpenKeychain"
  TAG_VERSION: "v6.0.4"
  TAG_BUILD: "-b"
  TAG_REF: "0000000"
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  #  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #  alias: ${{ secrets.ANDROID_ALIAS }}
  #  keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
  #  keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}  

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        # uses: deep-soft/checkout@v4
        # was: fetch-depth: 1
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Get ref, set build version
        shell: bash
        run: |
          _ref_all_=$(git log -1 --format='%H');
          # _ref_=$(echo ${_ref_all_::7});
          _ref_org_=${{ env.TAG_REF }};
          _ref_len_="${#_ref_org_}";
          _ref_=$(echo ${_ref_all_::$_ref_len_});
          _prg_version_=$(grep "versionName " "${{ env.PRG_NAME }}/build.gradle" | awk -F '"' '{print $2}') || true;
          echo "TAG_REF=$_ref_" >> $GITHUB_ENV;
          _build_=${{ env.TAG_BUILD }}.$_ref_;
          echo "TAG_BUILD=$_build_" >> $GITHUB_ENV;
          echo "PRG_VERSION=$_prg_version_" >> $GITHUB_ENV;
          echo "TAG_VERSION=$_prg_version_" >> $GITHUB_ENV;

      - name: Print ref, build version
        shell: bash
        run: |
          echo "VER: ${{ env.PRG_VERSION }}";
          echo "TAG: ${{ env.TAG_VERSION }}";
          echo "REF: ${{ env.TAG_REF }}";
          echo "BLD: ${{ env.TAG_BUILD }}";
          echo "${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}-${{ env.TAG_BUILD }}" > _tag_name_.txt
          echo "${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}-${{ env.TAG_BUILD }}" > ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.txt

      - name: Create source archive
        continue-on-error: true
        uses: deep-soft/zip-release@v2.2
        with:
          type: 'tar.xz'
          filename: "${{ env.PRG_NAME }}-src-${{ env.PRG_VERSION }}-${{ env.TAG_BUILD }}"
          directory: '.'
          exclusions: ''
          recursive_exclusions: ''
          ignore_git: 'no'
          path: '.'
          env_variable: ASSET_SRC
        # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Publish src archive
        continue-on-error: true
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{ env.ASSET_SRC }}

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Build ${{ env.PRG_NAME }} application
        run: ./gradlew :OpenKeychain:assemble

      - name: Upload Artifact
        uses: deep-soft/upload-artifact@v4
        with:
          name: upload-artifact
          path: |
            ./${{ env.PRG_NAME }}/build/outputs/apk/

# full begin
      - name: Copy apk from outputs/
        shell: bash
        run: |
          set -x
          mkdir -p signed-apk
          echo "LIST: " ./${{ env.PRG_NAME }}/build/outputs/apk/
          ls -l ./${{ env.PRG_NAME }}/build/outputs/apk/
          cp ./${{ env.PRG_NAME }}/build/outputs/apk/*.apk ./signed-apk/
          echo "LIST: " ./signed-apk/
          ls -l ./signed-apk/
          mv ./signed-apk/${{ env.PRG_NAME }}-release-unsigned.apk ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk
          echo "LIST: " ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk
          ls -l ./signed-apk/

      - name: Sign app APK
        uses: deep-soft/sign-android-release@v1
        if: env.ANDROID_SIGNING_KEY != null
        id: sign-app
        with:
          releaseDirectory: ./signed-apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Artifacts
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/upload-artifact@v4
        with:
          name: ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.apk
          path: ${{steps.sign-app.outputs.signedReleaseFile}}

      - name: Publish signed apk package
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ${{steps.sign-app.outputs.signedReleaseFile}}
            ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.txt
            _tag_name_.txt

      - name: Publish version build - signed apk package
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{steps.sign-app.outputs.signedReleaseFile}}
            ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.txt
            _tag_name_.txt

      - name: Publish unsigned apk package
        if: env.ANDROID_SIGNING_KEY == null
        uses: deep-soft/action-gh-release@v2.1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-unsigned.apk
            _tag_name_.txt
# full end
